@startuml
skinparam handwritten true
skinparam monochrome true
skinparam DefaultFontName xkcd Script
' skinparam packageStyle rectangle
left to right direction

title Testing Use Case Diagram

actor "Food Critic" as foodCritic
actor "Chef" as chef

rectangle "Reviewing Food" {
  foodCritic -- (Eat food)
  foodCritic -- (Drink)
  foodCritic -- (Review)
  foodCritic -- (Pay for food)
  (Cook food) -- chef
  (Eat food) .> (Cook food) : include
  (Review) .> (Eat food) : include
  (Review) .> (Drink) : include
}

' actor customer
' actor employee
' rectangle checkout {
'   customer -- (checkout)
'   (checkout) .> (payment) : include
'   (help) .> (checkout) : extends
'   (checkout) -- employee
' }


@enduml
