@startuml
skinparam handwritten true
skinparam monochrome true
skinparam DefaultFontName xkcd Script

title Banking app

User --> (Use)
"Use the application" as (Use)

Admin --> (Main Admin)
"Admin the application" as (Main Admin)

left to right direction
actor "Food Critic" as fc
rectangle Restaurant {
  usecase "Eat Food" as UC1
  usecase "Pay for Food" as UC2
  usecase "Drink" as UC3
}
fc --> UC1
fc --> UC2
fc --> UC3

@enduml
